### ISSUE TITLE
Fully capture ruleset metadata

### ISSUE THREAD

**Issue by fabianvf** [konveyor/windup-shim#53]
Need to evaluate the following fields, determine whether they belong in the analyzer-lsp, and update the code to include them in the ruleset.yaml:

- [x] Dependencies (should be able to drop this)
- [x] SourceTechnology (should convert to tag)
- [x] TargetTechnology (should convert to tag)
- [ ] Phase (could convert to tag)
- [x] ExecuteAfter (used only in `windup-rulesets/rules/rules-reviewed/technology-usage/spring-catchall.windup.xml`)
- [x] ExecuteBefore (seems unused in windup)
- [x] OverrideRules (seems unused in windup)

**Comment by shawn-hurley** [comment]
Marking the ones we can drop as completed.
